android.experimental.enableNewResourceShrinker.preciseShrinking=true
android.enableAppCompileTimeRClass=true
android.useAndroidX=true
org.gradle.jvmargs=-Xmx2048m
org.gradle.parallel=true
org.gradle.vfs.watch=true
android.r8.maxWorkers=4

# Custom static keystore variables for lsplugin.apksign
KEYSTORE_FILE=app/debug.keystore
KEYSTORE_PASSWORD=android
KEY_ALIAS=androiddebugkey
KEY_PASSWORD=android
